log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://postgres:password@localhost:5432/erc20?sslmode=disable"

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: erc20-transfers-storage-svc
  service_port: 80
